version: '3.6'

services:

  mysql:
    image: mariadb:10.4.8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - ./mariadb:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=56781234
    - TZ=Asia/Bangkok
    ports:
    - "1985:3306" # cong tu ngoai vao host la 3307, cong tu host vao container la 3306
    expose:
    - 1985

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.5
    restart: always
    depends_on:
    - mysql
    environment:
    - PMA_HOST=mysql
    ports:
    - "8080:80"
  backend_api:
    # image:
    container_name: backend_api
    build:
      context: ./wedding-backend
    restart: always
    ports:
        - "5000:5000"
    depends_on:
        - mysql
    expose:
        - 5000
