# default config
service:
  name: Wedding API
  description: Wedding Service
  apiVersion: '0.0.1'
  baseUrl: '/api/v1/wedding'

server:
  host: '127.0.0.1'
  port: 3000
  hostname: 127.0.0.1:3000

swagger:
  path: /docs
  schema: http

database:
  mysql: 
    host: '127.0.0.1'
    port: 3306
    username: root
    password: '123456'
    database: 'wedding'

oauth:
  google:
    clientId: '484546127494-gb3hh4t70htknres4ubrs615qsavn827.apps.googleusercontent.com'
    clientSecret: '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'
    callbackURL: '/auth/google/callback'